#!/usr/bin/env python3
"""
Fetch 20 network jokes daily and send via email
"""

import os
import smtplib
import requests
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def fetch_jokes(count=20):
    """Fetch jokes from a public API"""
    jokes = []
    try:
        for i in range(count):
            response = requests.get('https://official-joke-api.appspot.com/random_joke', timeout=5)
            if response.status_code == 200:
                joke_data = response.json()
                jokes.append({
                    'type': joke_data.get('type', 'general'),
                    'setup': joke_data.get('setup', ''),
                    'punchline': joke_data.get('punchline', '')
                })
    except Exception as e:
        print(f"Error fetching jokes: {e}")
    
    return jokes

def format_report(jokes):
    """Format jokes into a nice email report"""
    date_str = datetime.now().strftime('%Y-%m-%d')
    
    html_content = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #4CAF50; color: white; padding: 20px; text-align: center; border-radius: 5px; }}
            .joke {{ background-color: #f5f5f5; padding: 15px; margin: 10px 0; border-left: 4px solid #4CAF50; border-radius: 3px; }}
            .setup {{ font-weight: bold; color: #2196F3; }}
            .punchline {{ margin-top: 8px; color: #333; font-style: italic; }}
            .footer {{ text-align: center; color: #999; font-size: 12px; margin-top: 30px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>😄 Daily Joke Report</h1>
                <p>{date_str}</p>
            </div>
    """
    
    for i, joke in enumerate(jokes, 1):
        html_content += f"""
            <div class="joke">
                <strong>#{i}</strong>
                <div class="setup">{joke['setup']}</div>
                <div class="punchline">{joke['punchline']}</div>
            </div>
        """
    
    html_content += """
            <div class="footer">
                <p>Automatically generated by Daily Report Bot</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    return html_content

def send_email(recipient, subject, html_content):
    """Send email using SMTP"""
    sender = "noreply@github.com"
    password = os.getenv('SMTP_PASSWORD')
    
    if not password:
        print("Error: EMAIL_PASSWORD not set in secrets")
        return False
    
    try:
        msg = MIMEMultipart('alternative')
        msg['Subject'] = subject
        msg['From'] = sender
        msg['To'] = recipient
        
        msg.attach(MIMEText(html_content, 'html'))
        
        # For Outlook
        with smtplib.SMTP('smtp-mail.outlook.com', 587) as server:
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)
        
        print(f"Email sent successfully to {recipient}")
        return True
        
    except Exception as e:
        print(f"Error sending email: {e}")
        return False

def main():
    email = os.getenv('EMAIL_ADDRESS')
    
    print("Fetching 20 jokes...")
    jokes = fetch_jokes(20)
    
    if not jokes:
        print("Failed to fetch jokes")
        return
    
    print(f"Successfully fetched {len(jokes)} jokes")
    
    date_str = datetime.now().strftime('%Y-%m-%d')
    subject = f"Daily Joke Report - {date_str}"
    
    html_content = format_report(jokes)
    
    if email:
        print(f"Sending report to {email}...")
        send_email(email, subject, html_content)
    else:
        print("EMAIL_ADDRESS not set")
        print(html_content)

if __name__ == '__main__':
    main()
